import Head from "next/head";

import Header from "@/components/atoms/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header description="내가 정한것을 좋아하는 정한 👋">
          jeonghan_log
        </Header>
      </main>
    </>
  );
}
